// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    Collapse: typeof import('./src/components/Collapse.vue')['default']
    Controls: typeof import('./src/components/Controls.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MainList: typeof import('./src/components/MainList.vue')['default']
    Stratagem: typeof import('./src/components/Stratagem.vue')['default']
  }
}

export { }
